### ISSUE TITLE
SQL requirement for creating table

### ISSUE THREAD

**Issue by Meikelrizkyhartawan** [imJMaximo/LibRecord#1]
Can you provide the SQL for the tables ?

**Comment by Meikelrizkyhartawan** [comment]
1. BookmarkFragment

CREATE TABLE books (
    bookid INT AUTO_INCREMENT PRIMARY KEY,
    BookName VARCHAR(255) NOT NULL,
    AuthorName VARCHAR(255) NOT NULL,
    Year VARCHAR(255),
    Category VARCHAR(255),
    Publisher VARCHAR(255),	
    ISBN VARCHAR(255),
    Language VARCHAR(255),
    BookImages VARCHAR(255),
);

CREATE TABLE bookmark (
    bookid INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
);


2. AccountData

CREATE TABLE AccountData (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    passwword VARCHAR(255) NOT NULL,
    LibID VARCHAR(255) NOT NULL,
);

3. reservationrecord

CREATE TABLE AccountData (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    date VARCHAR(255) NOT NULL,
    date_return VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
);

**Comment by imJMaximo** [comment]
Hi Thank you for bringing this to my attention! I didn't realize that I forgot to upload the SQL for this project. I already uploaded it with file name Librecord.sql
